deCamelCase MOS return values
aristanetworks/pytest-netdut pull request #9
Opened 2022-11-08 21:20 UTC by romecode

Standardize to EOS. Add test case for translator.

2022-11-09 04:04 UTC, dcasnowdon requested changes
This looks good to me. I think the interface to the translator class could be more natural -- i.e. it's not just a method that we should assign, but the class itself, with several methods for different translation activities -- e.g. translating the CLI commands, and translating the returned json data. 

I think we should change that interface to the more natural style just because third parties may wish to build other translators and this is effectively a persistent API.

2022-11-10 23:47 UTC, romecode reviewed
Split up the translation functions.

2022-11-15 23:01 UTC, alexw-anet commented on src/pytest_netdut/wrappers.py
> +class EOS_MOS_Translator(Translator):
Can you give this a PascalCase style name please?

2022-11-15 23:11 UTC, alexw-anet commented on src/pytest_netdut/wrappers.py
> +    def __init__(self):
I think this should have a compatible signature with the base class.

Do we want `config_patterns` to be an argument, or is it always a static feature of the class?

2022-11-16 23:08 UTC, dcasnowdon approved these changes
I've added a couple of comments which might be good to fix up -- e.g. the docstrings. 

It would also be good to add some documentation about the translator to the README.md and the docstrings.

2022-11-16 23:08 UTC, dcasnowdon commented on src/pytest_netdut/wrappers.py
> +        """Returns a standardized key.
It's not clear from this docstring what this key is for. I think this is for translating json results?

2022-11-16 23:08 UTC, dcasnowdon commented on src/pytest_netdut/wrappers.py
> +            return self.process_dict(data)
Should this be called "translate_json_dict" or similar to make it more clear what this is doing?

2022-11-17 21:14 UTC, merged